config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  root :to => "grams#index"
  resources :grams
  resources :users
  match 'users/:id' => 'users#show', via: :get
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :gram
    belongs_to :user
end

app/models/gram.rb
class Gram < ApplicationRecord
    belongs_to :user
    has_one_attached :image

    has_many :comments, :dependent => :destroy

    def resize_image
        resized_image = MiniMagick::Image.read(image.download)
        resized_image = resized_image.resize "400x400"
        v_filename = image.filename
        v_content_type = image.content_type
        image.purge
        image.attach(io: File.open(resized_image.path), filename:  v_filename, content_type: v_content_type)
    end

    def image_format
        return unless image.attached?
        if image.blob.content_type.start_with? 'image/'
          if image.blob.byte_size > 10.megabytes
            errors.add(:image, 'size needs to be less than 10MB')
            image.purge
          else
            resize_image
          end
         else
           image.purge
           errors.add(:avatar, 'needs to be an image')
         end
       end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
  has_many :grams 
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :username, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :surname, :username, :email, :password, :current_password)}
  end

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to new_user_session_path, :notice => 'You must be signed in to do that!'
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @user = current_user
    @comment = @user.comments.create(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to :root, notice: "Comment was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to :root, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to :root, notice: "Comment successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content, :gram_id)  
    end
end

app/controllers/grams_controller.rb
class GramsController < ApplicationController
  before_action :authenticate_user!, except: :index
  def index
    @grams = Gram.all
    @comment = Comment.new
  end

  def edit
    @gram = Gram.find(params[:id])
  end

  def new
    @gram = Gram.new
  end

  def create
    @user = current_user
    @gram = @user.grams.create(create_gram_params)
    @gram.resize_image
    redirect_to grams_url
  end

  def update
    @gram = Gram.find(params[:id])
    respond_to do |format|
      if @gram.update(edit_gram_params)
        format.html { redirect_to :root, notice: "Gram was successfully updated." }
        format.json { render :show, status: :ok, location: @gram }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gram.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @gram = Gram.find(params[:id])
    @gram.destroy
    respond_to do |format|
      format.html { redirect_to :root, notice: "Gram was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
  def create_gram_params
    params.require(:gram).permit(:image, :description)
  end

  def edit_gram_params
    params.require(:gram).permit(:description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/grams_helper.rb
module GramsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class ="fields">
    <%= form.label :content, "Content" %><br />
      <%= form.text_field :content %>
      <%= form.hidden_field(:gram_id, value: @comment.gram.id) %>
    </div>
 

  <div class="actions">
    <%= form.submit "Post" %>
  </div>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', :root %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/grams/edit.html.erb
<%= form_for @gram do |f| %>
    <%= f.label :description, "Edit the description" %><br />
    <%= f.text_field :description %>
    <%= f.submit "Post" %>
<% end %>

app/views/grams/index.html.erb
<h1>Binstagram</h1>
<% @grams.reverse.each do |gram| %>
    <div>
<img src="<%= (url_for(gram.image)) %>"><br>
By <%= User.find(gram.user_id).username %><br> on <%= gram.created_at %>
<p><%= gram.description %></p>
<% if user_signed_in? && current_user.id == gram.user_id %>
<%= link_to "Edit this gram's description", edit_gram_path(gram) %>
<%= link_to "Delete this gram", gram_path(gram), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<ul>
<% gram.comments.reverse.each do |comment| %>
    <li><%= comment.content %> by <%= User.find(comment.user_id).username %> on <%= comment.created_at %>
    <% if user_signed_in? && current_user.id == comment.user_id %>
    <%= link_to "Edit this comment", edit_comment_path(comment) %>
    <%= link_to "Delete this comment", comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %>
    
    <% end %>
    </li>
    <% end %>
</ul>
<% if user_signed_in? %>
<%= form_for @comment do |f| %> 
    <%= f.label :content, "Comment" %><br />
    <%= f.text_field :content %>
    <%= f.hidden_field(:gram_id, value: gram.id) %>
    <%= f.submit "Post" %>
    <% end %>
    <% end %>
</div>
<% end %>

app/views/grams/new.html.erb
<%= form_for @gram do |f| %>
    <%= f.file_field :image %>
    <%= f.label :description, "Add a description (optional)" %><br />
    <%= f.text_field :description %>
    <%= f.submit "Post" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Binstagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg">
  <a class="navbar-brand" href="/">Binstagram</a>
  <ul class="navbar-nav">
  <% if user_signed_in? %>
  <span class="navbar-text">
  You are currently logged in as <a href="/users/<%= "#{current_user.id}" %>"><%= current_user.username %>.</a>
  </span>
  <li class="nav-item">
  <a class="nav-link" href="/grams/new">New Gram
  </a>
  </li>
  <li class="nav-item">
  <a class="nav-link" href="/users/sign_out">
  Sign out
  </a>
  </li>
  <% else %>
  <li class="nav-item">
  <a class="nav-link" href="/users/sign_up">
Sign up for Binstagram  </a>
  </li>
  <li class="nav-item">
  <a class="nav-link" href="/users/sign_in">
Sign in to Binstagram  </a>
  </li>
  <% end %>
  </ul>
  </nav>
  <div class="container">
  <% flash.each do |key, value| %>
    <div class="<%= key %>"><%= value %></div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>Your grams</h1>
<% if @user.grams.any? %>
<% @user.grams.reverse.each do |gram| %>
    <div>
<img src="<%= (url_for(gram.image)) %>"><br>
<p><%= gram.description %></p>
<% end %>
<% else %>
You haven't posted any grams yet! Why not <%= link_to "start now", new_gram_path %>?
<% end %>
<!-- <%= link_to "Update your details", edit_user_registration_path %> --!>